spring:
  application:
    name: ecommerce
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  jwt:
    secretKey: ${JWT_SECRET}
    refreshTokenExpiration: 604800 #7day
    accessTokenExpiration: 720 #12m
